### ISSUE TITLE
GPU Fraction pod remains in `pending` state

### ISSUE THREAD

**Issue by BhautikChudasama** [NVIDIA/KAI-Scheduler#65]
Recently I have installed `gpu-operator`, and `kai-scheduler` in my k3s, In my machine i have single GPU. I am able to create the normal gpu pod, but when i am trying to create `gpu-fraction` pod it stuck to pending state. I created the default, and test queue.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gpu-sharing
  labels:
    runai/queue: test
  annotations:
    gpu-fraction: "0.1"
    gpu-fraction-num-devices: "1"
spec:
  runtimeClassName: nvidia
  schedulerName: kai-scheduler
  containers:
    - name: ubuntu
      image: ubuntu
      args: ["sleep", "infinity"]
```

One thing I don't understand why it is trying to create reservation multiple times?

![Image](https://github.com/user-attachments/assets/ca852622-de13-4e84-9931-5425a9131a9f)

Failed Reservation pod
![Image](https://github.com/user-attachments/assets/605a037c-815a-4612-8b73-e9118f1a241e)
