### ISSUE TITLE
When the CPU value in the test queue is larger than that in the default queue, the queue can be created normally.

### ISSUE THREAD

**Issue by mupeifeiyi** [NVIDIA/KAI-Scheduler#81]
When I use the following yaml file to create a queue, I can create the queue resource normally.
```
apiVersion: scheduling.run.ai/v2
kind: Queue
metadata:
  name: default
spec:
  resources:
    cpu:
      quota: 2000
      limit: 2000
      overQuotaWeight: 1
    gpu:
      quota: -1
      limit: -1
      overQuotaWeight: 1
    memory:
      quota: -1
      limit: -1
      overQuotaWeight: 1
---
apiVersion: scheduling.run.ai/v2
kind: Queue
metadata:
  name: test
spec:
  parentQueue: default
  resources:
    cpu:
      quota: 3000
      limit: 3000
      overQuotaWeight: 1
    gpu:
      quota: -1
      limit: -1
      overQuotaWeight: 1
    memory:
      quota: -1
      limit: -1
      overQuotaWeight: 1
```

The error is only reported when creating a pod using the test queue: 
`OverLimit: default quota has reached the allowable limit of CPU cores. Limit is 2 cores, currently 0 cores allocated and workload requested 3 cores`

I think the user should be reminded of the value conflict when creating it.
